/**
 * Copies the three typefaces Docento uses into `fonts/`, and writes the licence
 * and provenance record that has to travel with them.
 *
 * ## Why the files are copied rather than imported from the packages
 *
 * `next/font/local` needs a real path at build time, and the design system has
 * to work with no network access and no third-party font request at runtime.
 * Copying the WOFF2 the vendored packages already ship gives that, and keeps
 * the licence texts next to the files they cover rather than somewhere in
 * `node_modules` that a deployment does not carry.
 *
 * Run with `pnpm --filter @docento/ui fonts:sync`. The output is committed, so
 * this only runs when a typeface is added or a version moves.
 */
import { createHash } from 'node:crypto'
import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

import { dependencyDir, manifest, packageRoot } from './lib/package-path.mjs'

const root = packageRoot(import.meta.url)
const fontsDir = join(root, 'fonts')
const licencesDir = join(fontsDir, 'licences')

/** Every font file this script is responsible for, and where it comes from. */
const FONTS = [
  {
    output: 'geist-sans-variable.woff2',
    from: 'geist/dist/fonts/geist-sans/Geist-Variable.woff2',
    family: 'Geist Sans',
    role: 'Application UI and body text',
    package: 'geist',
    licence: 'OFL-1.1',
  },
  {
    output: 'geist-mono-variable.woff2',
    from: 'geist/dist/fonts/geist-mono/GeistMono-Variable.woff2',
    family: 'Geist Mono',
    role: 'Code and technical identifiers',
    package: 'geist',
    licence: 'OFL-1.1',
  },
  {
    output: 'newsreader-latin-wght-normal.woff2',
    from: '@fontsource-variable/newsreader/files/newsreader-latin-wght-normal.woff2',
    family: 'Newsreader',
    role: 'Marketing headlines',
    package: '@fontsource-variable/newsreader',
    licence: 'OFL-1.1',
  },
  {
    output: 'newsreader-latin-wght-italic.woff2',
    from: '@fontsource-variable/newsreader/files/newsreader-latin-wght-italic.woff2',
    family: 'Newsreader',
    role: 'Marketing headline emphasis',
    package: '@fontsource-variable/newsreader',
    licence: 'OFL-1.1',
  },
]

/** Licence files to retain, per package. Copied as-is, with their own names. */
const LICENCE_FILES = {
  geist: ['LICENSE.txt', 'LICENSE', 'license.txt'],
  '@fontsource-variable/newsreader': ['LICENSE', 'LICENSE.txt'],
}

function resolveInPackage(specifier) {
  const [name, ...rest] = specifier.startsWith('@')
    ? [
        specifier.split('/').slice(0, 2).join('/'),
        ...specifier.split('/').slice(2),
      ]
    : [specifier.split('/')[0], ...specifier.split('/').slice(1)]

  return join(dependencyDir(root, name), ...rest)
}

async function version(name) {
  return manifest(dependencyDir(root, name)).version
}

async function findLicence(name) {
  const dir = dependencyDir(root, name)

  for (const file of LICENCE_FILES[name] ?? ['LICENSE', 'LICENSE.txt']) {
    const candidate = join(dir, file)
    try {
      await readFile(candidate)
      return candidate
    } catch {
      // Try the next candidate.
    }
  }
  return null
}

async function sha256(path) {
  const contents = await readFile(path)
  return createHash('sha256').update(contents).digest('hex')
}

async function main() {
  await mkdir(fontsDir, { recursive: true })
  await mkdir(licencesDir, { recursive: true })

  const records = []

  for (const font of FONTS) {
    const source = resolveInPackage(font.from)
    const destination = join(fontsDir, font.output)

    await copyFile(source, destination)

    records.push({
      ...font,
      version: await version(font.package),
      sha256: await sha256(destination),
    })
  }

  const packages = [...new Set(FONTS.map((font) => font.package))]
  const licenceLines = []

  for (const name of packages) {
    const licence = await findLicence(name)

    if (!licence) {
      throw new Error(
        `No licence file found in ${name}. Refusing to copy a font whose licence this repository cannot retain.`,
      )
    }

    const output = join(licencesDir, `${name.replace('/', '-')}-LICENSE.txt`)
    await copyFile(licence, output)
    licenceLines.push(
      `- \`${name}\` — retained as \`fonts/licences/${name.replace('/', '-')}-LICENSE.txt\``,
    )
  }

  const document = `# Bundled typefaces

Generated by \`scripts/sync-fonts.mjs\`. Do not edit by hand: re-run the script
after changing a font package version, and commit the result.

Every file below ships inside the application bundle and is served from our own
origin. There is no third-party font request at runtime, and no font is loaded
on a surface that does not use it — the marketing site loads Newsreader, the
application surfaces load Geist.

| File | Family | Role | Source package | Version | Licence |
| --- | --- | --- | --- | --- | --- |
${records
  .map(
    (record) =>
      `| \`${record.output}\` | ${record.family} | ${record.role} | \`${record.package}\` | ${record.version} | ${record.licence} |`,
  )
  .join('\n')}

## Verification

SHA-256 of each committed file, so a file that changed without this document
changing is visible in review:

${records.map((record) => `- \`${record.output}\` — \`${record.sha256}\``).join('\n')}

## Licence texts

All three typefaces are licensed under the SIL Open Font License 1.1, which
permits bundling and redistribution:

${licenceLines.join('\n')}

The upstream projects:

- Geist Sans and Geist Mono — https://github.com/vercel/geist-font
- Newsreader — https://github.com/productiontype/Newsreader
`

  await writeFile(join(fontsDir, 'LICENCES.md'), document, 'utf8')

  process.stdout.write(
    `Synced ${records.length} font files and ${packages.length} licence texts into packages/ui/fonts.\n`,
  )
}

main().catch((error) => {
  process.stderr.write(`${error.stack ?? error.message}\n`)
  process.exit(1)
})
