import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

/** The package directory: this file sits in `src/__tests__`. */
const packageRoot = fileURLToPath(new URL('../..', import.meta.url))

/**
 * Brand asset gate.
 *
 * The SVG files in `assets/` are generated by `scripts/build-wordmark.mjs` from
 * the same data the React components read. These assertions exist because the
 * failure mode of a generated asset is silence: a wordmark that renders empty is
 * a valid SVG, and what catches it is a test that opens the file and checks the
 * paths are there.
 */

const assets = join(packageRoot, 'assets')

function read(name: string) {
  const path = join(assets, name)

  expect(
    existsSync(path),
    `Missing brand asset ${name}. Run brand:wordmark.`,
  ).toBe(true)

  return readFileSync(path, 'utf8')
}

const LOCKUPS = [
  'lockup-horizontal.svg',
  'lockup-horizontal-on-light.svg',
  'lockup-horizontal-on-dark.svg',
]

describe('the symbol', () => {
  it('is three shapes: a page, a bowl and a stem', () => {
    const data = JSON.parse(
      readFileSync(join(packageRoot, 'src/brand/symbol-paths.json'), 'utf8'),
    ) as { paths: Record<string, string> }

    expect(Object.keys(data.paths).sort()).toEqual([
      'bowl',
      'leftPage',
      'rightPage',
    ])

    for (const [name, path] of Object.entries(data.paths)) {
      expect(path.startsWith('M'), `${name} is not a path`).toBe(true)
      expect(path.length, `${name} is suspiciously short`).toBeGreaterThan(40)
      expect(path.endsWith('Z'), `${name} is not closed`).toBe(true)
    }
  })

  it('ships a self-contained SVG with a square viewBox', () => {
    const svg = read('symbol.svg')

    expect(svg).toContain('viewBox="0 0 34 34"')
    expect(svg.match(/<path /g)).toHaveLength(3)
    expect(svg).toContain('aria-label="Docento"')
  })

  it('has a colour variant for each background it is placed on', () => {
    expect(read('symbol-on-light.svg')).toContain('fill="#202820"')
    expect(read('symbol-on-dark.svg')).toContain('fill="#F1F3ED"')
  })
})

describe('the wordmark', () => {
  it('is outlines, not text that depends on a font being installed', () => {
    const svg = read('wordmark.svg')

    expect(svg).not.toContain('<text')
    expect(svg).not.toContain('font-family')
    expect(svg.match(/<path /g)?.length).toBe('Docento'.length)
  })

  it('declares the same geometry the React component renders', async () => {
    const module = (await import('../brand/wordmark-paths')) as {
      WORDMARK_VIEWBOX: string
      WORDMARK_WIDTH: number
      WORDMARK_HEIGHT: number
      WORDMARK_PATHS: readonly string[]
      WORDMARK_TEXT: string
    }

    expect(module.WORDMARK_TEXT).toBe('Docento')
    expect(module.WORDMARK_PATHS).toHaveLength('Docento'.length)
    expect(module.WORDMARK_PATHS.every((path) => path.startsWith('M'))).toBe(
      true,
    )
    expect(module.WORDMARK_VIEWBOX).toBe(
      `0 0 ${module.WORDMARK_WIDTH} ${module.WORDMARK_HEIGHT}`,
    )
    expect(module.WORDMARK_WIDTH).toBeGreaterThan(module.WORDMARK_HEIGHT)
  })
})

describe('the horizontal lockup', () => {
  it.each(LOCKUPS)('%s places the symbol before the wordmark', (name) => {
    const svg = read(name)
    const translations = [...svg.matchAll(/translate\(([\d.-]+)/g)].map(
      (match) => Number(match[1]),
    )

    // Two groups: the symbol at the origin, the wordmark shifted past it.
    expect(svg.match(/<g transform/g)).toHaveLength(2)
    expect(Math.min(...translations)).toBeLessThanOrEqual(0)
    expect(Math.max(...translations)).toBeGreaterThan(0)
  })

  it('ships a light and a dark variant', () => {
    expect(read('lockup-horizontal-on-light.svg')).toContain('fill="#202820"')
    expect(read('lockup-horizontal-on-dark.svg')).toContain('fill="#F1F3ED"')
  })
})

describe('the bundled typefaces', () => {
  it('records provenance and a licence for every committed font file', () => {
    const record = readFileSync(join(packageRoot, 'fonts/LICENCES.md'), 'utf8')

    for (const file of [
      'geist-sans-variable.woff2',
      'geist-mono-variable.woff2',
      'newsreader-latin-wght-normal.woff2',
      'newsreader-latin-wght-italic.woff2',
    ]) {
      expect(
        existsSync(join(packageRoot, 'fonts', file)),
        `${file} is missing`,
      ).toBe(true)
      expect(record, `${file} is not in LICENCES.md`).toContain(file)
    }

    expect(record).toContain('OFL-1.1')
  })
})
